source: _source
destination: _site
baseurl: "" # The subpath of your site. Use "" if you're hosting a blog at the root level.
url: "http://linuxsimba.com" # the base hostname & protocol for your site
title: "Linux Simba"
twitter_username: 'linuxsimba'
social_media_btn:
  - name: 'twitter'
    url: "https://twitter.com/intent/follow?original_referer=http%3A%2F%2Flinuxsimba.com&amp;region=follow_link&amp;screen_name=linuxsimba&amp;tw_p=followbutton"
    title: "Follow Us (@linuxsimba) on Twitter"
    id: 'twitter_btn'
# This is used by feed.xml. Uncomment if you want to use it.
# description: "..."
markdown: redcarpet
gems:
    - jekyll-gist
    - jekyll-last-modified-at
exclude:
  - "README.md"
  - "CHANGELOG.md"
  - "CNAME"
  - "Gemfile"
  - "Gemfile.lock"
  - "Guardfile"
permalink: :title
defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
